### ISSUE TITLE
由于解压缩后文件夹名称与 Action.php 中路径名称不一致，导致启用时出错

### ISSUE THREAD

**Issue by liliang13** [phpgao/BaiduSubmit#1]
由于 Action.php 中路径为：
`$this->_dir = '.' . __TYPECHO_PLUGIN_DIR__ . '/BaiduSubmit/inc/';`

而解压后的文件夹名称为 BaiduSubmit-0.2 或 BaiduSubmit-master 因此造成上传插件后启用时出错。

**Comment by phpgao** [comment]
感谢反馈！
